name: Feature request
description: Create a feature request to improve the tools.
title: 'Feature Request: '
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        ## Feature Description
        Provide a clear and concise description of the feature you would like to see added.

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Describe the feature you’d like to see implemented.
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Provide any relevant context, use cases, or screenshots.
